import os
from pathlib import Path

from PIL import Image

from schemas.question import Question, QuestionImage, QuestionType, ValidationStatus
from services.image_service import IMAGE_TYPES
from utils.files import DATA_DIR, EXTRACTED_IMAGE_DIR, UPLOAD_DIR


# ---------------------------------------------------------------------------
# Special path generated by question_normalizer for filename-only references
# whose real asset could not be resolved.
#
# Example:
#   filename = "missing.png"
#   generated path =
#   uploads/images/missing/missing.png
#
# Such a reference is a WARNING, not an ERROR.
# ---------------------------------------------------------------------------
MISSING_IMAGE_PLACEHOLDER_PREFIX = "uploads/images/missing/"


def is_unresolved_filename_reference(image: QuestionImage) -> bool:
    """
    Return True when the image was created from a filename-only reference
    that could not be resolved to an actual asset.

    We support both:
      1. the explicit marker added by question_normalizer
      2. the generated placeholder path

    Supporting both makes the validator robust even if old QuestionImage
    objects were created before the marker was introduced.
    """

    image_id = (image.id or "").strip()

    if image_id.startswith("__unresolved_filename__:"):
        return True

    normalized_path = str(image.path or "").replace("\\", "/").lower()

    return normalized_path.startswith(
        MISSING_IMAGE_PLACEHOLDER_PREFIX
    )


def image_file(image: QuestionImage) -> Path | None:
    """
    Resolve a referenced image safely.

    Supported references:
    - Absolute paths inside the application's upload/extracted-image
      directories.
    - Relative paths beginning with:
        uploads/
        extracted_images/

    Returns the resolved file path only when the file actually exists.
    """

    path = Path(image.path)

    if path.is_absolute():
        resolved = path.resolve()

        allowed_roots = (
            UPLOAD_DIR.resolve(),
            EXTRACTED_IMAGE_DIR.resolve(),
        )

        if not any(
            resolved == root or root in resolved.parents
            for root in allowed_roots
        ):
            return None

        return resolved if resolved.is_file() else None

    normalized = str(image.path).replace("\\", "/")

    if not normalized.startswith(
        (
            "uploads/",
            "extracted_images/",
        )
    ):
        return None

    candidate = (DATA_DIR / normalized).resolve()

    allowed_roots = (
        UPLOAD_DIR.resolve(),
        EXTRACTED_IMAGE_DIR.resolve(),
    )

    if not any(
        candidate == root or root in candidate.parents
        for root in allowed_roots
    ):
        return None

    return candidate if candidate.is_file() else None


def image_problem(image: QuestionImage) -> str | None:
    """
    Validate an image reference and return a machine-readable problem.

    Possible results:
        None
        missing
        unsupported
        oversized
        invalid dimensions
        unreadable
    """

    file_path = image_file(image)

    if not file_path:
        return "missing"

    if file_path.suffix.lower() not in IMAGE_TYPES:
        return "unsupported"

    max_size_mb = max(
        1,
        int(os.getenv("MAX_IMAGE_SIZE_MB", "10")),
    )

    if file_path.stat().st_size > max_size_mb * 1024 * 1024:
        return "oversized"

    try:
        with Image.open(file_path) as asset:
            if asset.width < 1 or asset.height < 1:
                return "invalid dimensions"

            asset.verify()

    except Exception:
        return "unreadable"

    return None


class ValidationService:
    def validate_questions(
        self,
        questions: list[Question],
    ) -> list[Question]:

        seen_ids: set[str] = set()
        seen_numbers: set[int] = set()

        validated: list[Question] = []

        for question in questions:

            warnings = list(question.warnings)
            status = ValidationStatus.valid

            # ===========================================================
            # QUESTION ID
            # ===========================================================

            if "Duplicate question ID." in warnings:
                status = ValidationStatus.error

            if not question.question_text.strip():
                warnings.append(
                    "Question text is missing."
                )
                status = ValidationStatus.error

            if question.id in seen_ids:
                warnings.append(
                    "Duplicate question ID."
                )
                status = ValidationStatus.error

            seen_ids.add(question.id)

            # ===========================================================
            # QUESTION NUMBER
            # ===========================================================

            if question.question_number is not None:

                if question.question_number in seen_numbers:
                    warnings.append(
                        "Duplicate question number."
                    )
                    status = ValidationStatus.error

                seen_numbers.add(
                    question.question_number
                )

            # ===========================================================
            # OPTIONS
            # ===========================================================

            option_ids = {
                option.id.upper()
                for option in question.options
            }

            if len(option_ids) != len(question.options):
                warnings.append(
                    "Duplicate option IDs."
                )
                status = ValidationStatus.error

            if (
                question.question_type
                == QuestionType.single_choice
                and len(question.options) < 2
            ):
                warnings.append(
                    "Single-choice question should have "
                    "at least two options."
                )
                status = ValidationStatus.error

            # ===========================================================
            # CORRECT ANSWER
            # ===========================================================

            if question.correct_answer:

                missing = [
                    answer
                    for answer in question.correct_answer
                    if answer.upper() not in option_ids
                ]

                if missing and option_ids:
                    warnings.append(
                        "Correct answer does not match an option."
                    )
                    status = ValidationStatus.error

            else:

                warnings.append(
                    "Correct answer is missing or uncertain."
                )

                if status != ValidationStatus.error:
                    status = ValidationStatus.warning

            # ===========================================================
            # IMAGE VALIDATION
            # ===========================================================

            images = [
                *question.question_images,
                *(
                    image
                    for option in question.options
                    for image in option.images
                ),
            ]

            if question.explanation:
                images.extend(
                    question.explanation.images
                )

            seen_image_ids: set[str] = set()

            for image in images:

                # -------------------------------------------------------
                # Duplicate image reference
                # -------------------------------------------------------

                if image.id and image.id in seen_image_ids:

                    warnings.append(
                        "Duplicate image reference."
                    )

                    if status != ValidationStatus.error:
                        status = ValidationStatus.warning

                if image.id:
                    seen_image_ids.add(image.id)

                # -------------------------------------------------------
                # Check actual file
                # -------------------------------------------------------

                problem = image_problem(image)

                if not problem:
                    continue

                image_name = (
                    image.filename
                    or Path(image.path).name
                )

                # -------------------------------------------------------
                # MISSING IMAGE
                # -------------------------------------------------------

                if problem == "missing":

                    # ===================================================
                    # IMPORTANT:
                    #
                    # Filename-only unresolved reference:
                    #
                    # {"filename": "missing.png"}
                    #
                    # -> WARNING
                    #
                    # Explicit missing path:
                    #
                    # {"path": "extracted_images/missing.png"}
                    #
                    # -> ERROR
                    # ===================================================

                    if is_unresolved_filename_reference(image):

                        warning = (
                            f"Referenced image not found: "
                            f"{image_name}"
                        )

                        warnings.append(warning)

                        if status != ValidationStatus.error:
                            status = ValidationStatus.warning

                    else:

                        warning = (
                            f"Image file does not exist: "
                            f"{image.path}"
                        )

                        warnings.append(warning)

                        status = ValidationStatus.error

                # -------------------------------------------------------
                # OTHER IMAGE PROBLEMS
                # -------------------------------------------------------

                else:

                    warnings.append(
                        f"Image is {problem}: {image.path}"
                    )

                    status = ValidationStatus.error

            # ===========================================================
            # QUESTION TYPE
            # ===========================================================

            if question.question_type == QuestionType.unknown:

                warnings.append(
                    "Question type is uncertain."
                )

                if status != ValidationStatus.error:
                    status = ValidationStatus.warning

            # ===========================================================
            # SECTION
            # ===========================================================

            if (
                question.section is not None
                and not question.section.strip()
            ):

                warnings.append(
                    "Section is blank."
                )

                if status != ValidationStatus.error:
                    status = ValidationStatus.warning

            # ===========================================================
            # TOPIC
            # ===========================================================

            if (
                question.topic is not None
                and not question.topic.strip()
            ):

                warnings.append(
                    "Topic is blank."
                )

                if status != ValidationStatus.error:
                    status = ValidationStatus.warning

            # ===========================================================
            # FINALIZE
            # ===========================================================

            question.warnings = sorted(
                set(warnings)
            )

            question.validation_status = status

            validated.append(question)

        return validated


def summarize_validation(
    questions: list[Question],
) -> dict[str, int]:

    return {
        "questions_found": len(questions),

        "valid": sum(
            1
            for question in questions
            if question.validation_status
            == ValidationStatus.valid
        ),

        "warnings": sum(
            1
            for question in questions
            if question.validation_status
            == ValidationStatus.warning
        ),

        "errors": sum(
            1
            for question in questions
            if question.validation_status
            == ValidationStatus.error
        ),
    }




# import os
# from pathlib import Path

# from PIL import Image

# from schemas.question import Question, QuestionImage, QuestionType, ValidationStatus
# from services.image_service import IMAGE_TYPES
# from utils.files import DATA_DIR, EXTRACTED_IMAGE_DIR, UPLOAD_DIR


# def image_file(image: QuestionImage) -> Path | None:
#     path = Path(image.path)
#     if path.is_absolute():
#         resolved = path.resolve()
#         if not any(root.resolve() in resolved.parents for root in (UPLOAD_DIR, EXTRACTED_IMAGE_DIR)):
#             return None
#         return resolved if resolved.is_file() else None
#     normalized = str(image.path).replace("\\", "/")
#     if not normalized.startswith(("uploads/", "extracted_images/")):
#         return None
#     candidate = (DATA_DIR / normalized).resolve()
#     return candidate if candidate.is_file() else None


# def image_problem(image: QuestionImage) -> str | None:
#     file_path = image_file(image)
#     if not file_path:
#         return "missing"
#     if file_path.suffix.lower() not in IMAGE_TYPES:
#         return "unsupported"
#     if file_path.stat().st_size > max(1, int(os.getenv("MAX_IMAGE_SIZE_MB", "10"))) * 1024 * 1024:
#         return "oversized"
#     try:
#         with Image.open(file_path) as asset:
#             if asset.width < 1 or asset.height < 1:
#                 return "invalid dimensions"
#             asset.verify()
#     except Exception:
#         return "unreadable"
#     return None


# class ValidationService:
#     def validate_questions(self, questions: list[Question]) -> list[Question]:
#         seen_ids: set[str] = set()
#         seen_numbers: set[int] = set()
#         validated: list[Question] = []
#         for question in questions:
#             warnings = list(question.warnings)
#             status = ValidationStatus.valid

#             if "Duplicate question ID." in warnings:
#                 status = ValidationStatus.error

#             if not question.question_text.strip():
#                 warnings.append("Question text is missing.")
#                 status = ValidationStatus.error

#             if question.id in seen_ids:
#                 warnings.append("Duplicate question ID.")
#                 status = ValidationStatus.error
#             seen_ids.add(question.id)

#             if question.question_number is not None:
#                 if question.question_number in seen_numbers:
#                     warnings.append("Duplicate question number.")
#                     status = ValidationStatus.error
#                 seen_numbers.add(question.question_number)

#             option_ids = {option.id.upper() for option in question.options}
#             if len(option_ids) != len(question.options):
#                 warnings.append("Duplicate option IDs.")
#                 status = ValidationStatus.error
#             if question.question_type == QuestionType.single_choice and len(question.options) < 2:
#                 warnings.append("Single-choice question should have at least two options.")
#                 status = ValidationStatus.error

#             if question.correct_answer:
#                 missing = [answer for answer in question.correct_answer if answer.upper() not in option_ids]
#                 if missing and option_ids:
#                     warnings.append("Correct answer does not match an option.")
#                     status = ValidationStatus.error
#             else:
#                 warnings.append("Correct answer is missing or uncertain.")
#                 if status != ValidationStatus.error:
#                     status = ValidationStatus.warning

#             images = [*question.question_images, *(image for option in question.options for image in option.images)]
#             if question.explanation:
#                 images.extend(question.explanation.images)
#             seen_image_ids: set[str] = set()
#             for image in images:
#                 if image.id and image.id in seen_image_ids:
#                     warnings.append("Duplicate image reference.")
#                     if status != ValidationStatus.error:
#                         status = ValidationStatus.warning
#                 if image.id:
#                     seen_image_ids.add(image.id)
#                 problem = image_problem(image)
#                 if problem:
#                     missing = image.filename or Path(image.path).name
#                     if problem == "missing" and any(item == f"Referenced image not found: {missing}" for item in warnings):
#                         if status != ValidationStatus.error:
#                             status = ValidationStatus.warning
#                     else:
#                         warnings.append(f"Image is {problem}: {image.path}")
#                         status = ValidationStatus.error

#             if question.question_type == QuestionType.unknown:
#                 warnings.append("Question type is uncertain.")
#                 if status != ValidationStatus.error:
#                     status = ValidationStatus.warning

#             if question.section is not None and not question.section.strip():
#                 warnings.append("Section is blank.")
#                 if status != ValidationStatus.error:
#                     status = ValidationStatus.warning
#             if question.topic is not None and not question.topic.strip():
#                 warnings.append("Topic is blank.")
#                 if status != ValidationStatus.error:
#                     status = ValidationStatus.warning

#             question.warnings = sorted(set(warnings))
#             question.validation_status = status
#             validated.append(question)
#         return validated


# def summarize_validation(questions: list[Question]) -> dict[str, int]:
#     return {
#         "questions_found": len(questions),
#         "valid": sum(1 for question in questions if question.validation_status == ValidationStatus.valid),
#         "warnings": sum(1 for question in questions if question.validation_status == ValidationStatus.warning),
#         "errors": sum(1 for question in questions if question.validation_status == ValidationStatus.error),
#     }



# import os
# from pathlib import Path

# from PIL import Image

# from schemas.question import Question, QuestionImage, QuestionType, ValidationStatus
# from services.image_service import IMAGE_TYPES
# from utils.files import DATA_DIR, EXTRACTED_IMAGE_DIR, UPLOAD_DIR


# def image_file(image: QuestionImage) -> Path | None:
#     """
#     Resolve a referenced image safely.

#     Supported references:
#     - Absolute paths inside the application's upload/extracted-image directories.
#     - Relative paths beginning with:
#         uploads/
#         extracted_images/

#     Returns the resolved file path only when the file actually exists.
#     """
#     path = Path(image.path)

#     if path.is_absolute():
#         resolved = path.resolve()

#         allowed_roots = (
#             UPLOAD_DIR.resolve(),
#             EXTRACTED_IMAGE_DIR.resolve(),
#         )

#         if not any(
#             resolved == root or root in resolved.parents
#             for root in allowed_roots
#         ):
#             return None

#         return resolved if resolved.is_file() else None

#     normalized = str(image.path).replace("\\", "/")

#     if not normalized.startswith(("uploads/", "extracted_images/")):
#         return None

#     candidate = (DATA_DIR / normalized).resolve()

#     allowed_roots = (
#         UPLOAD_DIR.resolve(),
#         EXTRACTED_IMAGE_DIR.resolve(),
#     )

#     if not any(
#         candidate == root or root in candidate.parents
#         for root in allowed_roots
#     ):
#         return None

#     return candidate if candidate.is_file() else None


# def image_problem(image: QuestionImage) -> str | None:
#     """
#     Validate an image reference and return a machine-readable problem.
#     """
#     file_path = image_file(image)

#     if not file_path:
#         return "missing"

#     if file_path.suffix.lower() not in IMAGE_TYPES:
#         return "unsupported"

#     max_size_mb = max(
#         1,
#         int(os.getenv("MAX_IMAGE_SIZE_MB", "10")),
#     )

#     if file_path.stat().st_size > max_size_mb * 1024 * 1024:
#         return "oversized"

#     try:
#         with Image.open(file_path) as asset:
#             if asset.width < 1 or asset.height < 1:
#                 return "invalid dimensions"

#             asset.verify()

#     except Exception:
#         return "unreadable"

#     return None


# class ValidationService:
#     def validate_questions(self, questions: list[Question]) -> list[Question]:
#         seen_ids: set[str] = set()
#         seen_numbers: set[int] = set()

#         validated: list[Question] = []

#         for question in questions:
#             warnings = list(question.warnings)
#             status = ValidationStatus.valid

#             # ---------------------------------------------------------
#             # Question ID validation
#             # ---------------------------------------------------------
#             if "Duplicate question ID." in warnings:
#                 status = ValidationStatus.error

#             if not question.question_text.strip():
#                 warnings.append("Question text is missing.")
#                 status = ValidationStatus.error

#             if question.id in seen_ids:
#                 warnings.append("Duplicate question ID.")
#                 status = ValidationStatus.error

#             seen_ids.add(question.id)

#             # ---------------------------------------------------------
#             # Question number validation
#             # ---------------------------------------------------------
#             if question.question_number is not None:
#                 if question.question_number in seen_numbers:
#                     warnings.append("Duplicate question number.")
#                     status = ValidationStatus.error

#                 seen_numbers.add(question.question_number)

#             # ---------------------------------------------------------
#             # Option validation
#             # ---------------------------------------------------------
#             option_ids = {
#                 option.id.upper()
#                 for option in question.options
#             }

#             if len(option_ids) != len(question.options):
#                 warnings.append("Duplicate option IDs.")
#                 status = ValidationStatus.error

#             if (
#                 question.question_type == QuestionType.single_choice
#                 and len(question.options) < 2
#             ):
#                 warnings.append(
#                     "Single-choice question should have at least two options."
#                 )
#                 status = ValidationStatus.error

#             # ---------------------------------------------------------
#             # Correct answer validation
#             # ---------------------------------------------------------
#             if question.correct_answer:
#                 missing = [
#                     answer
#                     for answer in question.correct_answer
#                     if answer.upper() not in option_ids
#                 ]

#                 if missing and option_ids:
#                     warnings.append(
#                         "Correct answer does not match an option."
#                     )
#                     status = ValidationStatus.error

#             else:
#                 warnings.append(
#                     "Correct answer is missing or uncertain."
#                 )

#                 if status != ValidationStatus.error:
#                     status = ValidationStatus.warning

#             # ---------------------------------------------------------
#             # Image validation
#             #
#             # Images can come from:
#             #   1. question images
#             #   2. option images
#             #   3. explanation images
#             #
#             # This is intentionally independent of AI.
#             # ---------------------------------------------------------
#             images = [
#                 *question.question_images,
#                 *(
#                     image
#                     for option in question.options
#                     for image in option.images
#                 ),
#             ]

#             if question.explanation:
#                 images.extend(question.explanation.images)

#             seen_image_ids: set[str] = set()

#             for image in images:

#                 # Duplicate image reference
#                 if image.id and image.id in seen_image_ids:
#                     warnings.append("Duplicate image reference.")

#                     if status != ValidationStatus.error:
#                         status = ValidationStatus.warning

#                 if image.id:
#                     seen_image_ids.add(image.id)

#                 problem = image_problem(image)

#                 if not problem:
#                     continue

#                 image_name = image.filename or Path(image.path).name

#                 # -----------------------------------------------------
#                 # Missing image
#                 #
#                 # Keep the exact wording expected by the existing test.
#                 # -----------------------------------------------------
#                 if problem == "missing":
#                     warning = (
#                         f"Image file does not exist: {image.path}"
#                     )

#                     warnings.append(warning)
#                     status = ValidationStatus.error

#                 # -----------------------------------------------------
#                 # Other image problems
#                 # -----------------------------------------------------
#                 else:
#                     warnings.append(
#                         f"Image is {problem}: {image.path}"
#                     )
#                     status = ValidationStatus.error

#             # ---------------------------------------------------------
#             # Question type validation
#             # ---------------------------------------------------------
#             if question.question_type == QuestionType.unknown:
#                 warnings.append(
#                     "Question type is uncertain."
#                 )

#                 if status != ValidationStatus.error:
#                     status = ValidationStatus.warning

#             # ---------------------------------------------------------
#             # Section / topic validation
#             # ---------------------------------------------------------
#             if question.section is not None and not question.section.strip():
#                 warnings.append("Section is blank.")

#                 if status != ValidationStatus.error:
#                     status = ValidationStatus.warning

#             if question.topic is not None and not question.topic.strip():
#                 warnings.append("Topic is blank.")

#                 if status != ValidationStatus.error:
#                     status = ValidationStatus.warning

#             # ---------------------------------------------------------
#             # Deduplicate warnings
#             # ---------------------------------------------------------
#             question.warnings = sorted(set(warnings))
#             question.validation_status = status

#             validated.append(question)

#         return validated


# def summarize_validation(
#     questions: list[Question],
# ) -> dict[str, int]:
#     return {
#         "questions_found": len(questions),
#         "valid": sum(
#             1
#             for question in questions
#             if question.validation_status == ValidationStatus.valid
#         ),
#         "warnings": sum(
#             1
#             for question in questions
#             if question.validation_status == ValidationStatus.warning
#         ),
#         "errors": sum(
#             1
#             for question in questions
#             if question.validation_status == ValidationStatus.error
#         ),
#     }


# import os
# from pathlib import Path

# from PIL import Image

# from schemas.question import Question, QuestionImage, QuestionType, ValidationStatus
# from services.image_service import IMAGE_TYPES
# from utils.files import DATA_DIR, EXTRACTED_IMAGE_DIR, UPLOAD_DIR


# def image_file(image: QuestionImage) -> Path | None:
#     """
#     Resolve a referenced image safely.

#     Supported references:
#     - Absolute paths inside uploads/extracted_images.
#     - Relative paths beginning with:
#         uploads/
#         extracted_images/

#     Filename-only references such as:
#         missing.png

#     are intentionally NOT resolved as filesystem paths.
#     They are handled as unresolved references by ValidationService.
#     """

#     path = Path(image.path)

#     # -------------------------------------------------------------
#     # Absolute paths
#     # -------------------------------------------------------------
#     if path.is_absolute():
#         resolved = path.resolve()

#         allowed_roots = (
#             UPLOAD_DIR.resolve(),
#             EXTRACTED_IMAGE_DIR.resolve(),
#         )

#         if not any(
#             resolved == root or root in resolved.parents
#             for root in allowed_roots
#         ):
#             return None

#         return resolved if resolved.is_file() else None

#     # -------------------------------------------------------------
#     # Relative paths
#     # -------------------------------------------------------------
#     normalized = str(image.path).replace("\\", "/").strip()

#     # Filename-only references are not filesystem references.
#     if not normalized.startswith(
#         ("uploads/", "extracted_images/")
#     ):
#         return None

#     candidate = (DATA_DIR / normalized).resolve()

#     allowed_roots = (
#         UPLOAD_DIR.resolve(),
#         EXTRACTED_IMAGE_DIR.resolve(),
#     )

#     if not any(
#         candidate == root or root in candidate.parents
#         for root in allowed_roots
#     ):
#         return None

#     return candidate if candidate.is_file() else None


# def image_problem(image: QuestionImage) -> str | None:
#     """
#     Validate an image.

#     Returns:
#         None
#         missing
#         unsupported
#         oversized
#         invalid dimensions
#         unreadable
#     """

#     file_path = image_file(image)

#     if not file_path:
#         return "missing"

#     # -------------------------------------------------------------
#     # File extension
#     # -------------------------------------------------------------
#     if file_path.suffix.lower() not in IMAGE_TYPES:
#         return "unsupported"

#     # -------------------------------------------------------------
#     # Maximum file size
#     # -------------------------------------------------------------
#     max_size_mb = max(
#         1,
#         int(os.getenv("MAX_IMAGE_SIZE_MB", "10")),
#     )

#     if file_path.stat().st_size > max_size_mb * 1024 * 1024:
#         return "oversized"

#     # -------------------------------------------------------------
#     # Image integrity
#     # -------------------------------------------------------------
#     try:
#         with Image.open(file_path) as asset:
#             if asset.width < 1 or asset.height < 1:
#                 return "invalid dimensions"

#             asset.verify()

#     except Exception:
#         return "unreadable"

#     return None


# def is_filename_only_image_reference(
#     image: QuestionImage,
# ) -> bool:
#     """
#     Determine whether an image is only a filename reference.

#     Examples that return True:

#         missing.png
#         figure1.jpg
#         diagram.jpeg

#     Examples that return False:

#         uploads/missing.png
#         extracted_images/question_1.png
#         C:/.../uploads/image.png

#     This is intentionally based on the reference itself and not
#     on whether image_file() could resolve it.
#     """

#     path_value = str(image.path or "").strip()
#     filename_value = str(image.filename or "").strip()

#     if not path_value:
#         return True

#     normalized_path = path_value.replace("\\", "/")

#     # Absolute path = explicit filesystem reference.
#     if Path(path_value).is_absolute():
#         return False

#     # Application-managed paths = explicit filesystem reference.
#     if normalized_path.startswith(
#         ("uploads/", "extracted_images/")
#     ):
#         return False

#     # If there is no directory component, it is a filename reference.
#     if "/" not in normalized_path:
#         return True

#     # Keep filename-only imports as unresolved references.
#     if filename_value:
#         normalized_filename = filename_value.replace("\\", "/")

#         if (
#             normalized_path == normalized_filename
#             and "/" not in normalized_filename
#         ):
#             return True

#     return False


# class ValidationService:
#     def validate_questions(
#         self,
#         questions: list[Question],
#     ) -> list[Question]:
#         """
#         Validate all imported questions.

#         Errors:
#             - Missing question text
#             - Duplicate question IDs
#             - Duplicate question numbers
#             - Invalid options
#             - Invalid answer references
#             - Explicit missing image paths
#             - Unsupported images
#             - Oversized images
#             - Corrupt/unreadable images

#         Warnings:
#             - Missing/uncertain answers
#             - Filename-only unresolved image references
#             - Unknown question type
#             - Blank optional metadata
#             - Duplicate image references
#         """

#         seen_ids: set[str] = set()
#         seen_numbers: set[int] = set()

#         validated: list[Question] = []

#         for question in questions:
#             warnings = list(question.warnings)
#             status = ValidationStatus.valid

#             # =====================================================
#             # QUESTION ID
#             # =====================================================

#             if "Duplicate question ID." in warnings:
#                 status = ValidationStatus.error

#             if not question.question_text.strip():
#                 warnings.append(
#                     "Question text is missing."
#                 )
#                 status = ValidationStatus.error

#             if question.id in seen_ids:
#                 warnings.append(
#                     "Duplicate question ID."
#                 )
#                 status = ValidationStatus.error

#             seen_ids.add(question.id)

#             # =====================================================
#             # QUESTION NUMBER
#             # =====================================================

#             if question.question_number is not None:

#                 if question.question_number in seen_numbers:
#                     warnings.append(
#                         "Duplicate question number."
#                     )
#                     status = ValidationStatus.error

#                 seen_numbers.add(
#                     question.question_number
#                 )

#             # =====================================================
#             # OPTIONS
#             # =====================================================

#             option_ids = {
#                 option.id.upper()
#                 for option in question.options
#             }

#             if len(option_ids) != len(question.options):
#                 warnings.append(
#                     "Duplicate option IDs."
#                 )
#                 status = ValidationStatus.error

#             if (
#                 question.question_type
#                 == QuestionType.single_choice
#                 and len(question.options) < 2
#             ):
#                 warnings.append(
#                     "Single-choice question should have "
#                     "at least two options."
#                 )
#                 status = ValidationStatus.error

#             # =====================================================
#             # CORRECT ANSWER
#             # =====================================================

#             if question.correct_answer:

#                 missing = [
#                     answer
#                     for answer in question.correct_answer
#                     if answer.upper() not in option_ids
#                 ]

#                 if missing and option_ids:
#                     warnings.append(
#                         "Correct answer does not match an option."
#                     )
#                     status = ValidationStatus.error

#             else:

#                 warnings.append(
#                     "Correct answer is missing or uncertain."
#                 )

#                 if status != ValidationStatus.error:
#                     status = ValidationStatus.warning

#             # =====================================================
#             # COLLECT ALL IMAGES
#             #
#             # Question images
#             # Option images
#             # Explanation images
#             # =====================================================

#             images = [
#                 *question.question_images,
#                 *(
#                     image
#                     for option in question.options
#                     for image in option.images
#                 ),
#             ]

#             if question.explanation:
#                 images.extend(
#                     question.explanation.images
#                 )

#             seen_image_ids: set[str] = set()

#             # =====================================================
#             # IMAGE VALIDATION
#             # =====================================================

#             for image in images:

#                 # -------------------------------------------------
#                 # Duplicate image reference
#                 # -------------------------------------------------

#                 if (
#                     image.id
#                     and image.id in seen_image_ids
#                 ):
#                     warnings.append(
#                         "Duplicate image reference."
#                     )

#                     if status != ValidationStatus.error:
#                         status = ValidationStatus.warning

#                 if image.id:
#                     seen_image_ids.add(image.id)

#                 # -------------------------------------------------
#                 # Validate image
#                 # -------------------------------------------------

#                 problem = image_problem(image)

#                 if not problem:
#                     continue

#                 image_name = (
#                     image.filename
#                     or Path(image.path).name
#                     or "unknown image"
#                 )

#                 # =================================================
#                 # MISSING IMAGE
#                 # =================================================

#                 if problem == "missing":

#                     # -------------------------------------------------
#                     # FILENAME ONLY
#                     #
#                     # Example:
#                     #
#                     # {
#                     #   "filename": "missing.png"
#                     # }
#                     #
#                     # This is a warning because the user may upload
#                     # the image separately later.
#                     # -------------------------------------------------

#                     if is_filename_only_image_reference(image):

#                         warnings.append(
#                             f"Referenced image not found: "
#                             f"{image_name}"
#                         )

#                         if status != ValidationStatus.error:
#                             status = ValidationStatus.warning

#                     # -------------------------------------------------
#                     # EXPLICIT PATH
#                     #
#                     # Example:
#                     #
#                     # extracted_images/missing.png
#                     #
#                     # The application expects this file to exist.
#                     # -------------------------------------------------

#                     else:

#                         warnings.append(
#                             f"Image file does not exist: "
#                             f"{image.path}"
#                         )

#                         status = ValidationStatus.error

#                 # =================================================
#                 # OTHER IMAGE ERRORS
#                 # =================================================

#                 else:

#                     warnings.append(
#                         f"Image is {problem}: "
#                         f"{image.path}"
#                     )

#                     status = ValidationStatus.error

#             # =====================================================
#             # QUESTION TYPE
#             # =====================================================

#             if question.question_type == QuestionType.unknown:

#                 warnings.append(
#                     "Question type is uncertain."
#                 )

#                 if status != ValidationStatus.error:
#                     status = ValidationStatus.warning

#             # =====================================================
#             # SECTION
#             # =====================================================

#             if (
#                 question.section is not None
#                 and not question.section.strip()
#             ):

#                 warnings.append(
#                     "Section is blank."
#                 )

#                 if status != ValidationStatus.error:
#                     status = ValidationStatus.warning

#             # =====================================================
#             # TOPIC
#             # =====================================================

#             if (
#                 question.topic is not None
#                 and not question.topic.strip()
#             ):

#                 warnings.append(
#                     "Topic is blank."
#                 )

#                 if status != ValidationStatus.error:
#                     status = ValidationStatus.warning

#             # =====================================================
#             # FINALIZE
#             # =====================================================

#             question.warnings = sorted(
#                 set(warnings)
#             )

#             question.validation_status = status

#             validated.append(question)

#         return validated


# def summarize_validation(
#     questions: list[Question],
# ) -> dict[str, int]:
#     """
#     Return validation statistics.
#     """

#     return {
#         "questions_found": len(questions),

#         "valid": sum(
#             1
#             for question in questions
#             if question.validation_status
#             == ValidationStatus.valid
#         ),

#         "warnings": sum(
#             1
#             for question in questions
#             if question.validation_status
#             == ValidationStatus.warning
#         ),

#         "errors": sum(
#             1
#             for question in questions
#             if question.validation_status
#             == ValidationStatus.error
#         ),
#     }